set_property PACKAGE_PIN D4 [get_ports clk_50M]
set_property IOSTANDARD LVCMOS33 [get_ports clk_50M]

set_property PACKAGE_PIN F12 [get_ports uart_rtl_0_txd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN F13 [get_ports  uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports  uart_rtl_0_rxd]

set_property PACKAGE_PIN T9 [get_ports  reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports  reset_rtl_0]





set_property IOSTANDARD LVCMOS33 [get_ports i_rst_n]
set_property PACKAGE_PIN N15 [get_ports i_rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports i_clk]
set_property PACKAGE_PIN U18 [get_ports i_clk]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cs[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cs[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cs[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cs[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cs[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cs[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cs[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_cs[0]}]
set_property PACKAGE_PIN F17 [get_ports {o_cs[0]}]
set_property PACKAGE_PIN F20 [get_ports {o_cs[1]}]
set_property PACKAGE_PIN G20 [get_ports {o_cs[2]}]
set_property PACKAGE_PIN H18 [get_ports {o_cs[3]}]
set_property PACKAGE_PIN L20 [get_ports {o_cs[4]}]
set_property PACKAGE_PIN M20 [get_ports {o_cs[5]}]
set_property PACKAGE_PIN K18 [get_ports {o_cs[6]}]
set_property PACKAGE_PIN J19 [get_ports {o_cs[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {o_dig_sel[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dig_sel[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dig_sel[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dig_sel[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dig_sel[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dig_sel[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dig_sel[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_dig_sel[0]}]
set_property PACKAGE_PIN K19 [get_ports {o_dig_sel[7]}]
set_property PACKAGE_PIN K17 [get_ports {o_dig_sel[6]}]
set_property PACKAGE_PIN M19 [get_ports {o_dig_sel[5]}]
set_property PACKAGE_PIN L19 [get_ports {o_dig_sel[4]}]
set_property PACKAGE_PIN J18 [get_ports {o_dig_sel[3]}]
set_property PACKAGE_PIN G19 [get_ports {o_dig_sel[2]}]
set_property PACKAGE_PIN F19 [get_ports {o_dig_sel[1]}]
set_property PACKAGE_PIN F16 [get_ports {o_dig_sel[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {i_key[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_key[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_key[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_key[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_key[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_key[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_key[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_key[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_key[0]}]
set_property PACKAGE_PIN N16 [get_ports {i_key[8]}]
set_property PACKAGE_PIN T17 [get_ports {i_key[7]}]
set_property PACKAGE_PIN R17 [get_ports {i_key[6]}]
set_property PACKAGE_PIN G17 [get_ports {i_key[5]}]
set_property PACKAGE_PIN E19 [get_ports {i_key[4]}]
set_property PACKAGE_PIN E18 [get_ports {i_key[3]}]
set_property PACKAGE_PIN G18 [get_ports {i_key[2]}]
set_property PACKAGE_PIN D20 [get_ports {i_key[1]}]
set_property PACKAGE_PIN D19 [get_ports {i_key[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {o_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_led[3]}]
set_property PACKAGE_PIN M14 [get_ports {o_led[0]}]
set_property PACKAGE_PIN M15 [get_ports {o_led[1]}]
set_property PACKAGE_PIN K16 [get_ports {o_led[2]}]
set_property PACKAGE_PIN J16 [get_ports {o_led[3]}]

set_property IOSTANDARD LVCMOS33 [get_ports {o_key_row[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_key_row[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_key_row[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {o_key_row[0]}]
set_property PACKAGE_PIN W18 [get_ports {o_key_row[3]}]
set_property PACKAGE_PIN W19 [get_ports {o_key_row[2]}]
set_property PACKAGE_PIN P14 [get_ports {o_key_row[1]}]
set_property PACKAGE_PIN R14 [get_ports {o_key_row[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {i_key_col[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_key_col[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_key_col[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {i_key_col[0]}]
set_property PACKAGE_PIN Y16 [get_ports {i_key_col[3]}]
set_property PACKAGE_PIN Y17 [get_ports {i_key_col[2]}]
set_property PACKAGE_PIN V15 [get_ports {i_key_col[1]}]
set_property PACKAGE_PIN W15 [get_ports {i_key_col[0]}]

create_clock -period 20.000 [get_ports i_clk]





create_generated_clock -name {Gen_Debouncer[3].Debouncer_inst/o_key_state_reg_n_1} -source [get_ports i_clk] -divide_by 1000000 [get_pins {Gen_Debouncer[3].Debouncer_inst/o_key_state_reg/Q}]
create_generated_clock -name {Gen_Debouncer[4].Debouncer_inst/o_key_state_reg_n_1} -source [get_ports i_clk] -divide_by 1000000 [get_pins {Gen_Debouncer[4].Debouncer_inst/o_key_state_reg/Q}]
create_generated_clock -name {Gen_Debouncer[5].Debouncer_inst/o_key_state_reg_n_1} -source [get_ports i_clk] -divide_by 1000000 [get_pins {Gen_Debouncer[5].Debouncer_inst/o_key_state_reg/Q}]
